trying to creat an iam user with vpc full access to get its access keys and use those for the workspace env vars - doesn't work.
I get the following:
Error: Saved plan is stale
The given plan file can no longer be applied because the state was changed by another operation after the plan was created.

suspect this is due to the env vars being created already and cant be updated, but i destroyed them (-target) and still can't apply... FML